<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="tortoisebot">

  <!-- Definir propriedades -->
  <xacro:property name="base_width" value="0.17"/>
  <xacro:property name="base_length" value="0.22"/>
  <xacro:property name="base_height" value="0.05"/>
  
  <xacro:property name="wheel_radius" value="0.0325"/>
  <xacro:property name="wheel_width" value="0.02"/>
  <xacro:property name="wheel_ygap" value="0.025"/>
  <xacro:property name="wheel_zoff" value="0.02"/>
  <xacro:property name="wheel_xoff" value="0.08"/>

  <!-- Incluir macros de sensores -->
  <xacro:include filename="$(find tortoisebot_description)/urdf/sensors.xacro"/>
  <xacro:include filename="$(find tortoisebot_description)/urdf/materials.xacro"/>

  <!-- Link base -->
  <link name="base_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${base_length} ${base_width} ${base_height}"/>
      </geometry>
      <material name="blue"/>
    </visual>
    
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${base_length} ${base_width} ${base_height}"/>
      </geometry>
    </collision>
    
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="2.5"/>
      <inertia
        ixx="0.0395416666667" ixy="0" ixz="0"
        iyy="0.106208333333" iyz="0"
        izz="0.106208333333"/>
    </inertial>
  </link>

  <!-- Rodas -->
  <xacro:macro name="wheel" params="prefix x_reflect y_reflect">
    <link name="${prefix}_wheel">
      <visual>
        <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
        </geometry>
        <material name="black"/>
      </visual>
      
      <collision>
        <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
        </geometry>
      </collision>
      
      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="0.3"/>
        <inertia
          ixx="0.00032" ixy="0" ixz="0"
          iyy="0.00032" iyz="0"
          izz="0.00063"/>
      </inertial>
    </link>

    <joint name="${prefix}_wheel_joint" type="continuous">
      <parent link="base_link"/>
      <child link="${prefix}_wheel"/>
      <origin xyz="${x_reflect*wheel_xoff} ${y_reflect*(base_width/2+wheel_ygap)} ${-wheel_zoff}" rpy="0 0 0"/>
      <axis xyz="0 1 0"/>
    </joint>
  </xacro:macro>

  <!-- Instanciar as 4 rodas -->
  <xacro:wheel prefix="front_left" x_reflect="1" y_reflect="1"/>
  <xacro:wheel prefix="front_right" x_reflect="1" y_reflect="-1"/>
  <xacro:wheel prefix="rear_left" x_reflect="-1" y_reflect="1"/>
  <xacro:wheel prefix="rear_right" x_reflect="-1" y_reflect="-1"/>

  <!-- Suporte do LiDAR -->
  <link name="lidar_support">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder radius="0.02" length="0.15"/>
      </geometry>
      <material name="white"/>
    </visual>
    
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder radius="0.02" length="0.15"/>
      </geometry>
    </collision>
    
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="0.1"/>
      <inertia
        ixx="0.000188" ixy="0" ixz="0"
        iyy="0.000188" iyz="0"
        izz="0.00004"/>
    </inertial>
  </link>

  <joint name="lidar_support_joint" type="fixed">
    <parent link="base_link"/>
    <child link="lidar_support"/>
    <origin xyz="0 0 ${base_height/2 + 0.075}" rpy="0 0 0"/>
  </joint>

  <!-- LiDAR Frame -->
  <link name="laser_frame">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder radius="0.05" length="0.04"/>
      </geometry>
      <material name="red"/>
    </visual>
    
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder radius="0.05" length="0.04"/>
      </geometry>
    </collision>
    
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="0.15"/>
      <inertia
        ixx="0.000375" ixy="0" ixz="0"
        iyy="0.000375" iyz="0"
        izz="0.000375"/>
    </inertial>
  </link>

  <joint name="laser_joint" type="fixed">
    <parent link="lidar_support"/>
    <child link="laser_frame"/>
    <origin xyz="0 0 ${0.075 + 0.02}" rpy="0 0 0"/>
  </joint>

  <!-- Incluir sensores -->
  <xacro:rplidar_a1m8 parent="laser_frame"/>
  <xacro:ultrasonic_hc_sr04 parent="base_link" prefix="front"/>
  <xacro:webcam_lenovo parent="base_link"/>

  <!-- Plugin Gazebo para movimento diferencial -->
  <gazebo>
    <plugin name="differential_drive_controller" filename="libgazebo_ros_diff_drive.so">
      <update_rate>30</update_rate>
      <left_joint>rear_left_wheel_joint</left_joint>
      <right_joint>rear_right_wheel_joint</right_joint>
      <wheel_separation>${base_width+2*wheel_ygap}</wheel_separation>
      <wheel_diameter>${2*wheel_radius}</wheel_diameter>
      <max_wheel_torque>20</max_wheel_torque>
      <max_wheel_acceleration>1.0</max_wheel_acceleration>
      <command_topic>cmd_vel</command_topic>
      <publish_odom>true</publish_odom>
      <publish_odom_tf>true</publish_odom_tf>
      <publish_wheel_tf>true</publish_wheel_tf>
      <odometry_topic>odom</odometry_topic>
      <odometry_frame>odom</odometry_frame>
      <robot_base_frame>base_link</robot_base_frame>
    </plugin>
  </gazebo>

</robot>
